/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netz.view;

/**
 *
 * @author doerrlu76113
 */
public class View extends javax.swing.JFrame
{

    /**
     * @return the menuNewFile
     */
    public javax.swing.JMenuItem getMenuNewFile() {
        return menuNewFile;
    }

    /**
     * @return the menuOpen
     */
    public javax.swing.JMenuItem getMenuOpen() {
        return menuOpen;
    }

    /**
     * @return the menuPencilColor
     */
    public javax.swing.JMenuItem getMenuPencilColor() {
        return menuPencilColor;
    }

    /**
     * @return the menuPencilSize
     */
    public javax.swing.JMenuItem getMenuPencilSize() {
        return menuPencilSize;
    }

    /**
     * @return the menuPrint
     */
    public javax.swing.JMenuItem getMenuPrint() {
        return menuPrint;
    }

    /**
     * @return the menuSave
     */
    public javax.swing.JMenuItem getMenuSave() {
        return menuSave;
    }

    /**
     * @return the mnuFile
     */
    public javax.swing.JMenu getMnuFile() {
        return mnuFile;
    }

    /**
     * @return the spinSize
     */
    public javax.swing.JSpinner getSpinSize() {
        return spinSize;
    }

    /**
     * @return the tfUser
     */
    public javax.swing.JTextField getTfUser() {
        return tfUser;
    }

  /**
   * Creates new form Fenster
   */
  public View()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    label1 = new java.awt.Label();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jToolBar1 = new javax.swing.JToolBar();
    jLabel1 = new javax.swing.JLabel();
    tfUser = new javax.swing.JTextField();
    jToolBar3 = new javax.swing.JToolBar();
    lblPenSize = new javax.swing.JLabel();
    spinSize = new javax.swing.JSpinner();
    jPanel3 = new javax.swing.JPanel();
    jToolBar2 = new javax.swing.JToolBar();
    btnServerMode = new javax.swing.JButton();
    tfIP = new javax.swing.JTextField();
    tfPort = new javax.swing.JTextField();
    btnConnect = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tfMessage = new javax.swing.JTextArea();
    btnSend = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tfCommunikation = new javax.swing.JTextPane();
    grafikView1 = new netz.view.GrafikView();
    jMenuBar = new javax.swing.JMenuBar();
    mnuFile = new javax.swing.JMenu();
    menuNewFile = new javax.swing.JMenuItem();
    menuOpen = new javax.swing.JMenuItem();
    menuSave = new javax.swing.JMenuItem();
    menuPrint = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    menuPencilColor = new javax.swing.JMenuItem();
    menuPencilSize = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    label1.setText("label1");
    getContentPane().add(label1, java.awt.BorderLayout.PAGE_END);

    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

    java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
    flowLayout2.setAlignOnBaseline(true);
    jPanel2.setLayout(flowLayout2);

    jToolBar1.setRollover(true);

    jLabel1.setText("Username:");
    jToolBar1.add(jLabel1);

    tfUser.setText("Guest");
    tfUser.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        tfUserActionPerformed(evt);
      }
    });
    jToolBar1.add(tfUser);

    jToolBar3.setRollover(true);

    lblPenSize.setText("Size");
    jToolBar3.add(lblPenSize);

    spinSize.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
    jToolBar3.add(spinSize);

    jToolBar1.add(jToolBar3);

    jPanel2.add(jToolBar1);

    jPanel1.add(jPanel2);

    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0);
    flowLayout1.setAlignOnBaseline(true);
    jPanel3.setLayout(flowLayout1);

    jToolBar2.setRollover(true);

    btnServerMode.setText("ClientMode");
    btnServerMode.setFocusable(false);
    btnServerMode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnServerMode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnServerMode.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnServerModeActionPerformed(evt);
      }
    });
    jToolBar2.add(btnServerMode);

    tfIP.setText("127.0.0.1");
    tfIP.setAlignmentX(0.0F);
    tfIP.setRequestFocusEnabled(false);
    tfIP.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        tfIPActionPerformed(evt);
      }
    });
    jToolBar2.add(tfIP);

    tfPort.setText("35000");
    tfPort.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        tfPortActionPerformed(evt);
      }
    });
    jToolBar2.add(tfPort);

    btnConnect.setFocusable(false);
    btnConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnConnect.setLabel("Verbinden");
    btnConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnConnect.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnConnectActionPerformed(evt);
      }
    });
    jToolBar2.add(btnConnect);
    btnConnect.getAccessibleContext().setAccessibleName("Connect");

    jPanel3.add(jToolBar2);

    jPanel1.add(jPanel3);

    getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

    jPanel4.setLayout(new java.awt.BorderLayout(2, 2));

    jPanel5.setAlignmentX(0.0F);
    jPanel5.setAlignmentY(0.0F);
    jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

    jScrollPane1.setAutoscrolls(true);
    jScrollPane1.setRowHeaderView(null);

    tfMessage.setColumns(20);
    tfMessage.setRows(1);
    jScrollPane1.setViewportView(tfMessage);

    jPanel5.add(jScrollPane1);

    btnSend.setLabel("Senden");
    jPanel5.add(btnSend);

    jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

    jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

    tfCommunikation.setEditable(false);
    tfCommunikation.setBackground(new java.awt.Color(255, 255, 255));
    tfCommunikation.setMinimumSize(new java.awt.Dimension(62, 100));
    tfCommunikation.setSelectedTextColor(new java.awt.Color(0, 0, 0));
    jScrollPane2.setViewportView(tfCommunikation);

    jPanel6.add(jScrollPane2);

    grafikView1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel6.add(grafikView1);

    jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

    mnuFile.setMnemonic('F');
    mnuFile.setText("File");

    menuNewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    menuNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netz/view/icons/Add16.gif"))); // NOI18N
    menuNewFile.setText("New File");
    menuNewFile.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        menuNewFileActionPerformed(evt);
      }
    });
    mnuFile.add(menuNewFile);

    menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    menuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netz/view/icons/Open16.gif"))); // NOI18N
    menuOpen.setText("Open");
    mnuFile.add(menuOpen);

    menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    menuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netz/view/icons/Save16.gif"))); // NOI18N
    menuSave.setText("Save");
    menuSave.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        menuSaveActionPerformed(evt);
      }
    });
    mnuFile.add(menuSave);

    menuPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    menuPrint.setText("Print");
    mnuFile.add(menuPrint);

    jMenuBar.add(mnuFile);

    jMenu3.setMnemonic('P');
    jMenu3.setText("Pencil");

    menuPencilColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
    menuPencilColor.setText("Color");
    jMenu3.add(menuPencilColor);

    menuPencilSize.setText("Thickness");
    jMenu3.add(menuPencilSize);

    jMenuBar.add(jMenu3);

    setJMenuBar(jMenuBar);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void tfIPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfIPActionPerformed
  {//GEN-HEADEREND:event_tfIPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfIPActionPerformed

  private void btnConnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConnectActionPerformed
  {//GEN-HEADEREND:event_btnConnectActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnConnectActionPerformed

    private void btnServerModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnServerModeActionPerformed
    {//GEN-HEADEREND:event_btnServerModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServerModeActionPerformed

    private void tfPortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfPortActionPerformed
    {//GEN-HEADEREND:event_tfPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPortActionPerformed

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void menuNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNewFileActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new View().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnConnect;
  private javax.swing.JButton btnSend;
  private javax.swing.JButton btnServerMode;
  private netz.view.GrafikView grafikView1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenuBar jMenuBar;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JToolBar jToolBar2;
  private javax.swing.JToolBar jToolBar3;
  private java.awt.Label label1;
  private javax.swing.JLabel lblPenSize;
  private javax.swing.JMenuItem menuNewFile;
  private javax.swing.JMenuItem menuOpen;
  private javax.swing.JMenuItem menuPencilColor;
  private javax.swing.JMenuItem menuPencilSize;
  private javax.swing.JMenuItem menuPrint;
  private javax.swing.JMenuItem menuSave;
  private javax.swing.JMenu mnuFile;
  private javax.swing.JSpinner spinSize;
  private javax.swing.JTextPane tfCommunikation;
  private javax.swing.JTextField tfIP;
  private javax.swing.JTextArea tfMessage;
  private javax.swing.JTextField tfPort;
  private javax.swing.JTextField tfUser;
  // End of variables declaration//GEN-END:variables

    /**
     * @return the btnConnect
     */
    public javax.swing.JButton getBtnConnect()
    {
        return btnConnect;
    }

    /**
     * @param btnConnect the btnConnect to set
     */
    public void setBtnConnect(javax.swing.JButton btnConnect)
    {
        this.btnConnect = btnConnect;
    }


    /**
     * @return the label1
     */
    public java.awt.Label getLabel1()
    {
        return label1;
    }

    /**
     * @param label1 the label1 to set
     */
    public void setLabel1(java.awt.Label label1)
    {
        this.label1 = label1;
    }



    /**
     * @return the tfAdress
     */
    public javax.swing.JTextField getTfAdress()
    {
        return getTfIP();
    }

    /**
     * @param tfAdress the tfAdress to set
     */
    public void setTfAdress(javax.swing.JTextField tfAdress)
    {
        this.tfIP = tfAdress;
    }

    /**
     * @return the tfCommunikation
     */
    public javax.swing.JTextPane getTfCommunikation()
    {
        return tfCommunikation;
    }

    /**
     * @param tfCommunikation the tfCommunikation to set
     */
    public void setTfCommunikation(javax.swing.JTextPane tfCommunikation)
    {
        this.tfCommunikation = tfCommunikation;
    }

    /**
     * @return the tfMessage
     */
    public javax.swing.JTextArea getTfMessage()
    {
        return tfMessage;
    }

    /**
     * @param tfMessage the tfMessage to set
     */
    public void setTfMessage(javax.swing.JTextArea tfMessage)
    {
        this.tfMessage = tfMessage;
    }

    /**
     * @return the btnSend
     */
    public javax.swing.JButton getBtnSend()
    {
        return btnSend;
    }

    /**
     * @param btnSend the btnSend to set
     */
    public void setBtnSend(javax.swing.JButton btnSend)
    {
        this.btnSend = btnSend;
    }

    /**
     * @return the btnServerMode
     */
    public javax.swing.JButton getBtnServerMode()
    {
        return btnServerMode;
    }

    /**
     * @return the tfIP
     */
    public javax.swing.JTextField getTfIP()
    {
        return tfIP;
    }

    /**
     * @return the tfPort
     */
    public javax.swing.JTextField getTfPort()
    {
        return tfPort;
    }
}
