/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package synchronize.view;

/**
 *
 * @author le
 */
public class MainView extends javax.swing.JFrame
{

    /**
     * @return the lblCounter0
     */
    public javax.swing.JLabel getLblCounter0() {
        return lblCounter0;
    }

    /**
     * @return the lblCounter1
     */
    public javax.swing.JLabel getLblCounter1() {
        return lblCounter1;
    }

    /**
     * @return the lblCounter2
     */
    public javax.swing.JLabel getLblCounter2() {
        return lblCounter2;
    }

  /**
   * @return the btnStart
   */
  public javax.swing.JButton getBtnStart()
  {
    return btnStart;
  }

  /**
   * @return the btnStop
   */
  public javax.swing.JButton getBtnStop()
  {
    return btnStop;
  }

  /**
   * @return the lblCounter
   */
  public javax.swing.JLabel getLblCounter()
  {
    return getLblCounter0();
  }

  /**
   * Creates new form Fenster
   */
  public MainView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCounter0 = new javax.swing.JLabel();
        lblCounter1 = new javax.swing.JLabel();
        lblCounter2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        jPanel1.add(btnStart);

        btnStop.setText("Stop");
        jPanel1.add(btnStop);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        lblCounter0.setFont(new java.awt.Font("Cantarell", 0, 120)); // NOI18N
        lblCounter0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounter0.setText("1");
        lblCounter0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblCounter0.setName(""); // NOI18N
        jPanel2.add(lblCounter0);

        lblCounter1.setFont(new java.awt.Font("Cantarell", 0, 120)); // NOI18N
        lblCounter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounter1.setText("1");
        lblCounter1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(lblCounter1);

        lblCounter2.setFont(new java.awt.Font("Cantarell", 0, 120)); // NOI18N
        lblCounter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounter2.setText("1");
        lblCounter2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(lblCounter2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(297, 219));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new MainView().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCounter0;
    private javax.swing.JLabel lblCounter1;
    private javax.swing.JLabel lblCounter2;
    // End of variables declaration//GEN-END:variables
}
