/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netz.view;

/**
 *
 * @author doerrlu76113
 */
public class View extends javax.swing.JFrame
{

  /**
   * Creates new form Fenster
   */
  public View()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnServerMode = new javax.swing.JButton();
        tfIP = new javax.swing.JTextField();
        tfPort = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfCommunikation = new javax.swing.JTextPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        label1.setText("label1");
        getContentPane().add(label1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        jPanel1.add(jPanel2);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        jToolBar2.setRollover(true);

        btnServerMode.setText("ServerMode");
        btnServerMode.setFocusable(false);
        btnServerMode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServerMode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServerMode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnServerModeActionPerformed(evt);
            }
        });
        jToolBar2.add(btnServerMode);

        tfIP.setText("127.0.0.1");
        tfIP.setPreferredSize(new java.awt.Dimension(100, 24));
        tfIP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfIPActionPerformed(evt);
            }
        });
        jToolBar2.add(tfIP);

        tfPort.setText("35000");
        tfPort.setPreferredSize(new java.awt.Dimension(100, 24));
        tfPort.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfPortActionPerformed(evt);
            }
        });
        jToolBar2.add(tfPort);

        btnConnect.setFocusable(false);
        btnConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConnect.setLabel("Verbinden");
        btnConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConnect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConnectActionPerformed(evt);
            }
        });
        jToolBar2.add(btnConnect);
        btnConnect.getAccessibleContext().setAccessibleName("Connect");

        jPanel3.add(jToolBar2);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setRowHeaderView(null);

        tfMessage.setColumns(20);
        tfMessage.setRows(1);
        jScrollPane1.setViewportView(tfMessage);

        jPanel5.add(jScrollPane1);

        btnSend.setLabel("Senden");
        jPanel5.add(btnSend);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        tfCommunikation.setEditable(false);
        tfCommunikation.setBackground(new java.awt.Color(255, 255, 255));
        tfCommunikation.setText("Chatfenster");
        jScrollPane2.setViewportView(tfCommunikation);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jMenu1.setText("?");
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void tfIPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfIPActionPerformed
  {//GEN-HEADEREND:event_tfIPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfIPActionPerformed

  private void btnConnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConnectActionPerformed
  {//GEN-HEADEREND:event_btnConnectActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnConnectActionPerformed

    private void btnServerModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnServerModeActionPerformed
    {//GEN-HEADEREND:event_btnServerModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServerModeActionPerformed

    private void tfPortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfPortActionPerformed
    {//GEN-HEADEREND:event_tfPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPortActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new View().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnServerMode;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar2;
    private java.awt.Label label1;
    private javax.swing.JTextPane tfCommunikation;
    private javax.swing.JTextField tfIP;
    private javax.swing.JTextArea tfMessage;
    private javax.swing.JTextField tfPort;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnConnect
     */
    public javax.swing.JButton getBtnConnect()
    {
        return btnConnect;
    }

    /**
     * @param btnConnect the btnConnect to set
     */
    public void setBtnConnect(javax.swing.JButton btnConnect)
    {
        this.btnConnect = btnConnect;
    }


    /**
     * @return the label1
     */
    public java.awt.Label getLabel1()
    {
        return label1;
    }

    /**
     * @param label1 the label1 to set
     */
    public void setLabel1(java.awt.Label label1)
    {
        this.label1 = label1;
    }



    /**
     * @return the tfAdress
     */
    public javax.swing.JTextField getTfAdress()
    {
        return getTfIP();
    }

    /**
     * @param tfAdress the tfAdress to set
     */
    public void setTfAdress(javax.swing.JTextField tfAdress)
    {
        this.tfIP = tfAdress;
    }

    /**
     * @return the tfCommunikation
     */
    public javax.swing.JTextPane getTfCommunikation()
    {
        return tfCommunikation;
    }

    /**
     * @param tfCommunikation the tfCommunikation to set
     */
    public void setTfCommunikation(javax.swing.JTextPane tfCommunikation)
    {
        this.tfCommunikation = tfCommunikation;
    }

    /**
     * @return the tfMessage
     */
    public javax.swing.JTextArea getTfMessage()
    {
        return tfMessage;
    }

    /**
     * @param tfMessage the tfMessage to set
     */
    public void setTfMessage(javax.swing.JTextArea tfMessage)
    {
        this.tfMessage = tfMessage;
    }

    /**
     * @return the btnSend
     */
    public javax.swing.JButton getBtnSend()
    {
        return btnSend;
    }

    /**
     * @param btnSend the btnSend to set
     */
    public void setBtnSend(javax.swing.JButton btnSend)
    {
        this.btnSend = btnSend;
    }

    /**
     * @return the btnServerMode
     */
    public javax.swing.JButton getBtnServerMode()
    {
        return btnServerMode;
    }

    /**
     * @return the tfIP
     */
    public javax.swing.JTextField getTfIP()
    {
        return tfIP;
    }

    /**
     * @return the tfPort
     */
    public javax.swing.JTextField getTfPort()
    {
        return tfPort;
    }
}
