/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package commanddp.view;

/**
 *
 * @author doerrlu76113
 */
public class EditorView extends javax.swing.JFrame
{

    /**
     * @return the tContent
     */
    public javax.swing.JTable gettContent()
    {
        return tContent;
    }

    /**
     * @param tContent the tContent to set
     */
    public void settContent(javax.swing.JTable tContent)
    {
        this.tContent = tContent;
    }
  /**
   * @return the lblStatus
   */
  public java.awt.Label getLblStatus()
  {
    return lblStatus;
  }
  /**
   * @return the fcOpenSave
   */
  public javax.swing.JFileChooser getFcOpenSave()
  {
    return fcOpenSave;
  }

  /**
   * Creates new form Fenster
   */
  public EditorView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pu_add = new javax.swing.JMenuItem();
        pu_delet = new javax.swing.JMenuItem();
        fcOpenSave = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_open = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        btn_add = new javax.swing.JButton();
        btn_delet = new javax.swing.JButton();
        btn_undo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToolBar2 = new javax.swing.JToolBar();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tContent = new javax.swing.JTable();
        lblStatus = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_open = new javax.swing.JMenuItem();
        menu_save = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_add = new javax.swing.JMenuItem();
        menu_delet = new javax.swing.JMenuItem();
        menu_undo = new javax.swing.JMenuItem();

        jPopupMenu1.setToolTipText("gdxg");
        jPopupMenu1.setLabel("");
        jPopupMenu1.setName("test,"); // NOI18N

        pu_add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
        pu_add.setText("Hinzufügen");
        pu_add.setToolTipText("Zeile hinzufügen");
        jPopupMenu1.add(pu_add);

        pu_delet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        pu_delet.setText("Löschen");
        pu_delet.setToolTipText("Zeile Löschen");
        jPopupMenu1.add(pu_delet);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jToolBar1.setRollover(true);

        btn_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Open16.gif"))); // NOI18N
        btn_open.setToolTipText("Öffnen");
        btn_open.setFocusable(false);
        btn_open.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_open.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_open);

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Save16.gif"))); // NOI18N
        btn_save.setToolTipText("Speichern");
        btn_save.setFocusable(false);
        btn_save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_save.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_saveActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_save);

        jPanel2.add(jToolBar1);

        jToolBar3.setRollover(true);

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Add16.gif"))); // NOI18N
        btn_add.setToolTipText("Hinzufügen");
        btn_add.setFocusable(false);
        btn_add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_add.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(btn_add);

        btn_delet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Delete16.gif"))); // NOI18N
        btn_delet.setToolTipText("Löschen");
        btn_delet.setFocusable(false);
        btn_delet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_delet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_delet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_deletActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_delet);

        btn_undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Undo16.gif"))); // NOI18N
        btn_undo.setToolTipText("Rückgängig");
        btn_undo.setFocusable(false);
        btn_undo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_undo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(btn_undo);

        jPanel2.add(jToolBar3);

        jPanel1.add(jPanel2);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Search16.gif"))); // NOI18N
        jButton4.setToolTipText("Suchen");
        jPanel3.add(jButton4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Vorname", "Adresse", "E-Mail", "Telefon" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);

        jToolBar2.setRollover(true);

        jTextField1.setText("Suche...");
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 24));
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jTextField1);

        jPanel3.add(jToolBar2);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        tContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Kern", "Carmin", "Gogolstraße 14a, 90475 Nürnberg", "kernca71519@th-nuernberg.de", "+4915144241500"},
                {"Doerr", "Luka", "", "doerrlu76113@th-nuernberg.de", null},
                {"leere Zeile", null, null, null, null}
            },
            new String []
            {
                "Name", "Vorname", "Adresse", "E-Mail", "Telefon"
            }
        ));
        tContent.setToolTipText("");
        tContent.setComponentPopupMenu(jPopupMenu1);
        tContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tContent.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tContent.setMinimumSize(new java.awt.Dimension(650, 50));
        tContent.setPreferredSize(new java.awt.Dimension(650, 250));
        tContent.setShowGrid(true);
        jScrollPane1.setViewportView(tContent);
        if (tContent.getColumnModel().getColumnCount() > 0)
        {
            tContent.getColumnModel().getColumn(0).setMinWidth(100);
            tContent.getColumnModel().getColumn(1).setMinWidth(100);
            tContent.getColumnModel().getColumn(2).setMinWidth(200);
            tContent.getColumnModel().getColumn(3).setMinWidth(150);
            tContent.getColumnModel().getColumn(4).setMinWidth(100);
        }
        tContent.getAccessibleContext().setAccessibleParent(tContent);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblStatus.setName(""); // NOI18N
        lblStatus.setText("Datei: ");
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        jMenu1.setMnemonic('D');
        jMenu1.setText("Datei");

        menu_open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Open16.gif"))); // NOI18N
        menu_open.setMnemonic('O');
        menu_open.setText("Öffnen");
        menu_open.setToolTipText("Öffnet eine Datei");
        jMenu1.add(menu_open);

        menu_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Save16.gif"))); // NOI18N
        menu_save.setMnemonic('S');
        menu_save.setText("Speichern");
        menu_save.setToolTipText("Speichert eine Datei");
        menu_save.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menu_saveActionPerformed(evt);
            }
        });
        jMenu1.add(menu_save);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('B');
        jMenu2.setText("Bearbeiten");

        menu_add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
        menu_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Add16.gif"))); // NOI18N
        menu_add.setMnemonic('H');
        menu_add.setText("Hinzufügen");
        menu_add.setToolTipText("Zeile hinzufügen");
        jMenu2.add(menu_add);

        menu_delet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        menu_delet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Delete16.gif"))); // NOI18N
        menu_delet.setMnemonic('L');
        menu_delet.setText("Löschen");
        menu_delet.setToolTipText("Zeile Löschen");
        jMenu2.add(menu_delet);

        menu_undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/view/icons/Undo16.gif"))); // NOI18N
        menu_undo.setMnemonic('R');
        menu_undo.setText("Rückgägnig");
        menu_undo.setToolTipText("Aktion Rückgängig machen");
        jMenu2.add(menu_undo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void menu_saveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menu_saveActionPerformed
  {//GEN-HEADEREND:event_menu_saveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_menu_saveActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
  {//GEN-HEADEREND:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
  {//GEN-HEADEREND:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_deletActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_deletActionPerformed
    {//GEN-HEADEREND:event_btn_deletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deletActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_saveActionPerformed
    {//GEN-HEADEREND:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new EditorView().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delet;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_undo;
    private javax.swing.JFileChooser fcOpenSave;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private java.awt.Label lblStatus;
    private javax.swing.JMenuItem menu_add;
    private javax.swing.JMenuItem menu_delet;
    private javax.swing.JMenuItem menu_open;
    private javax.swing.JMenuItem menu_save;
    private javax.swing.JMenuItem menu_undo;
    private javax.swing.JMenuItem pu_add;
    private javax.swing.JMenuItem pu_delet;
    private javax.swing.JTable tContent;
    // End of variables declaration//GEN-END:variables

  /**
   * @return the btn_add
   */
  public javax.swing.JButton getBtnAdd()
  {
    return btn_add;
  }

  /**
   * @return the btn_delet
   */
  public javax.swing.JButton getBtnDelete()
  {
    return btn_delet;
  }

  /**
   * @return the btn_open
   */
  public javax.swing.JButton getBtnOpen()
  {
    return btn_open;
  }

  /**
   * @return the btn_redo
   */


  /**
   * @return the btn_save
   */
  public javax.swing.JButton getBtnSave()
  {
    return btn_save;
  }

  /**
   * @return the btn_undo
   */
  public javax.swing.JButton getBtnUndo()
  {
    return btn_undo;
  }

  /**
   * @return the menu_add
   */
  public javax.swing.JMenuItem getMenuAdd()
  {
    return menu_add;
  }

  /**
   * @return the menu_delet
   */
  public javax.swing.JMenuItem getMenuDelete()
  {
    return menu_delet;
  }

  /**
   * @return the menu_open
   */
  public javax.swing.JMenuItem getMenuOpen()
  {
    return menu_open;
  }

  /**
   * @return the menu_redo
   */

  /**
   * @return the menu_save
   */
  public javax.swing.JMenuItem getMenuSave()
  {
    return menu_save;
  }

  /**
   * @return the menu_undo
   */
  public javax.swing.JMenuItem getMenuUndo()
  {
    return menu_undo;
  }

  /**
   * @return the pu_add
   */
  public javax.swing.JMenuItem getPopAdd()
  {
    return pu_add;
  }

  /**
   * @return the pu_delet
   */
  public javax.swing.JMenuItem getPopDelete()
  {
    return pu_delet;
  }
}
